apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client-app
          image: reetesh-client
          imagePullPolicy: Never
          env:
            - name: VITE_SERVER_URL
              value: "/api"

---
apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
    - port: 8000
      targetPort: 8000
